name: build
on:
  push:
    branches:
      - master
    tags:
      - "!*" # Do not execute on tags
    paths:
      - src/*
      - __tests__/*
      - "*.json"
      - yarn.lock
  pull_request:
    paths:
      - "!*.MD"
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macOS-latest]
        node: ["12", "14", "16"]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test
